app:
  env: dev 
  gin_mode: debug 
  server_address: "0.0.0.0:8001"
  secret_key: "my_precious"
  s3_bucket_name: "recording_2"
  s3_endpoint_url: "*************"
  aws_region: ""
  aws_access_key: "*****************"
  aws_secret_access_key: "****************"

mongodb:
  url: "*******************"
  database: "record"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

portaone:
  username: "*********"
  password: "********"

# db:
#   url: "postgres://postgres:postgres@localhost/call_recording?sslmode=disable&timezone=UTC"

