app:
  env: dev 
  gin_mode: release 
  server_address: "0.0.0.0:8001"
  secret_key: "my_precious"
  s3_bucket_name: "recording"


db:
  url: "postgres://postgres:postgres@localhost/call-recording?sslmode=disable&timezone=UTC"

