app:
  env: dev 
  gin_mode: release 
  server_address: "0.0.0.0:8001"
  secret_key: "my_precious"
  s3_bucket_name: "recording"

mongodb:
  url: "mongodb://localhost:27017"
  database: "call_recording_service"

# db:
#   url: "postgres://postgres:postgres@localhost/call_recording?sslmode=disable&timezone=UTC"

